export const Boards = [
    '8-4-4 Curriculum',
    'A-Levels',
    'Abitur',
    'American Curriculum',
    'Australian Curriculum',
    'BTEC',
    'Brazilian National Curriculum',
    'British Curriculum',
    'CBC',
    'CBSE',
    'Cambridge',
    'Cambridge International',
    'Catholic Education',
    'Catholic School',
    'Charter',
    'Chinese National Curriculum',
    'Edexcel',
    'Egyptian National Curriculum',
    'Federal Board',
    'French Immersion',
    'French National Curriculum',
    'GCSE',
    'HKDSE',
    'Homeschool',
    'IB',
    'ICSE',
    'IEB',
    'Indian CBSE',
    'Indian ICSE',
    'Integrated Programme',
    'International French Baccalaureate',
    'International Schools',
    'Italian National Curriculum',
    'Japanese National Curriculum',
    'K-12 Curriculum',
    'Korean National Curriculum',
    'Madrasa Board',
    'Malaysian National Curriculum',
    'Mexican National Curriculum',
    'MOE Schools',
    'Montessori',
    'NCEA',
    'National Curriculum',
    'National Senior Certificate',
    'NECO',
    'Other',
    'Private',
    'Private Schools',
    'Public School',
    'Public School District',
    'Punjab Board',
    'RBSE',
    'Russian National Curriculum',
    'SA',
    'Saudi Ministry of Education',
    'Scottish Highers',
    'Sindh Board',
    'Spanish National Curriculum',
    'State Board',
    'State Curriculum',
    'Thai National Curriculum',
    'Turkish National Curriculum',
    'UAE Ministry of Education',
    'Vietnamese National Curriculum',
    'WAEC',
];
