import type { Metadata } from "next";
import "./globals.scss";
import Header from "@/components/layout/header/Header";
import { Toaster } from "sonner";
import Footer from "@/components/layout/footer/Footer";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <Header />
                {children}
                <Toaster
                    position="top-center"
                    visibleToasts={2}
                    expand={true}
                    richColors
                    duration={2000}
                />
                <Footer />
            </body>
        </html>
    );
}
